Chore/navbar mge9 ccps
froilanbuendia/aim-trainer pull request #12
Opened 2023-08-22 07:03 UTC by froilanbuendia

2023-08-23 16:34 UTC, froilanbuendia commented
<img width="1512" alt="image" src="https://github.com/froilanbuendia/aim-trainer/assets/80615020/5f0099f5-1a73-4bb5-a188-e4a632cfa53e">

2023-08-24 22:07 UTC, ficsby requested changes

2023-08-24 22:07 UTC, ficsby commented on frontend/src/components/navbar.css
> +  background: #006d77;
add position: fixed;

2023-08-24 23:26 UTC, froilanbuendia commented
<img width="1507" alt="image" src="https://github.com/froilanbuendia/aim-trainer/assets/80615020/a66481b6-3a1f-43c0-88fe-c1f319408c0b">

2023-08-25 06:31 UTC, ficsby approved these changes

2023-08-26 07:01 UTC, merged